name: api_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Screen Responsive
  flutter_screenutil: ^5.7.0

  # GetX
  get: ^4.6.5

  # Easyloading
  flutter_easyloading: ^3.0.5

  #
  flutter_localization: ^0.1.11

  # Fonts
  google_fonts: ^4.0.4

  #
  expandable_text: ^2.3.0
  flutter_linkify: ^6.0.0
  flutter_vector_icons: ^2.0.0

  cloud_firestore: ^4.8.2
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.0

  # Toast
  fluttertoast: ^8.2.2

  # Cache
  cached_network_image: ^3.2.3
  dio: ^5.2.1+1
  cookie_jar: ^4.0.5
  dio_cookie_manager: ^3.1.0
  shared_preferences: ^2.2.0
  package_info: ^2.0.2
  firebase_messaging: ^14.6.5
  flutter_local_notifications: ^15.1.0+1
  google_sign_in: ^6.1.4
  image_picker: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/images/slider.png

