class AppBanner{
  final int id;
  final String judul;
  final String deskripsi;
  final String thumbnailUrl;

  AppBanner(this.id, this.judul, this.deskripsi, this.thumbnailUrl);

}

// Sample Data
List<AppBanner> appBannerList = [
  AppBanner( 1, 'Sarang Walet Putih (Original)', 'Walet sarang-putih (bahasa Latin = Collocalia fuciphaga) adalah spesies burung  dari keluarga Apodidae, dari genus Aerodramus (Collocalia). Burung ini merupakan jenis burung pemakan serangga kecil yang merupakan salah satu burung yg memiliki kemampuan ekolokasi, Seperti halnya kelelawar, walet juga mampu melakukan ekolokasi, yakni kemampuan mengeluarkan suara berfrekuensi tertentu secara terputus-putus dan kemudian menangkap, kembali pantulan suara tersebut untuk menentukan jarak dan letak sebuah benda yang memantulkannya. Kemampuan ini memungkinkan walet untuk terbang/berburu di tempat yang gelap.', 'assets/images/slider.png'),
  AppBanner( 2, 'Sarang Walet Putih (Original)', 'Walet sarang-putih (bahasa Latin = Collocalia fuciphaga) adalah spesies burung  dari keluarga Apodidae, dari genus Aerodramus (Collocalia). Burung ini merupakan jenis burung pemakan serangga kecil yang merupakan salah satu burung yg memiliki kemampuan ekolokasi, Seperti halnya kelelawar, walet juga mampu melakukan ekolokasi, yakni kemampuan mengeluarkan suara berfrekuensi tertentu secara terputus-putus dan kemudian menangkap, kembali pantulan suara tersebut untuk menentukan jarak dan letak sebuah benda yang memantulkannya. Kemampuan ini memungkinkan walet untuk terbang/berburu di tempat yang gelap.', 'assets/images/slider.png'),
  AppBanner( 3, 'Sarang Walet Putih (Original)', 'Walet sarang-putih (bahasa Latin = Collocalia fuciphaga) adalah spesies burung  dari keluarga Apodidae, dari genus Aerodramus (Collocalia). Burung ini merupakan jenis burung pemakan serangga kecil yang merupakan salah satu burung yg memiliki kemampuan ekolokasi, Seperti halnya kelelawar, walet juga mampu melakukan ekolokasi, yakni kemampuan mengeluarkan suara berfrekuensi tertentu secara terputus-putus dan kemudian menangkap, kembali pantulan suara tersebut untuk menentukan jarak dan letak sebuah benda yang memantulkannya. Kemampuan ini memungkinkan walet untuk terbang/berburu di tempat yang gelap.', 'assets/images/slider.png'),
  AppBanner( 4, 'Sarang Walet Putih (Original)', 'Walet sarang-putih (bahasa Latin = Collocalia fuciphaga) adalah spesies burung  dari keluarga Apodidae, dari genus Aerodramus (Collocalia). Burung ini merupakan jenis burung pemakan serangga kecil yang merupakan salah satu burung yg memiliki kemampuan ekolokasi, Seperti halnya kelelawar, walet juga mampu melakukan ekolokasi, yakni kemampuan mengeluarkan suara berfrekuensi tertentu secara terputus-putus dan kemudian menangkap, kembali pantulan suara tersebut untuk menentukan jarak dan letak sebuah benda yang memantulkannya. Kemampuan ini memungkinkan walet untuk terbang/berburu di tempat yang gelap.', 'assets/images/slider.png'),
  AppBanner( 5, 'Sarang Walet Putih (Original)', 'Walet sarang-putih (bahasa Latin = Collocalia fuciphaga) adalah spesies burung  dari keluarga Apodidae, dari genus Aerodramus (Collocalia). Burung ini merupakan jenis burung pemakan serangga kecil yang merupakan salah satu burung yg memiliki kemampuan ekolokasi, Seperti halnya kelelawar, walet juga mampu melakukan ekolokasi, yakni kemampuan mengeluarkan suara berfrekuensi tertentu secara terputus-putus dan kemudian menangkap, kembali pantulan suara tersebut untuk menentukan jarak dan letak sebuah benda yang memantulkannya. Kemampuan ini memungkinkan walet untuk terbang/berburu di tempat yang gelap.', 'assets/images/slider.png')
];